// prettier-ignore
export const list = [
  { group: 1, code: 100, description: "Continue" },
  { group: 1, code: 101, description: "Switching protocols" },
  { group: 1, code: 102, description: "Processing" },
  { group: 1, code: 103, description: "Early Hints" },

  { group: 2, code: 200, description: "OK" },
  { group: 2, code: 201, description: "Created" },
  { group: 2, code: 202, description: "Accepted" },
  { group: 2, code: 203, description: "Non-Authoritative Information" },
  { group: 2, code: 204, description: "No Content" },
  { group: 2, code: 205, description: "Reset Content" },
  { group: 2, code: 206, description: "Partial Content" },
  { group: 2, code: 207, description: "Multi-Status" },
  { group: 2, code: 208, description: "Already Reported" },
  { group: 2, code: 226, description: "IM Used" },

  { group: 3, code: 300, description: "Multiple Choices" },
  { group: 3, code: 301, description: "Moved Permanently" },
  { group: 3, code: 302, description: "Found (Previously 'Moved Temporarily')" },
  { group: 3, code: 303, description: "See Other" },
  { group: 3, code: 304, description: "Not Modified" },
  { group: 3, code: 305, description: "Use Proxy" },
  { group: 3, code: 306, description: "Switch Proxy" },
  { group: 3, code: 307, description: "Temporary Redirect" },
  { group: 3, code: 308, description: "Permanent Redirect" },

  { group: 4, code: 400, description: "Bad Request" },
  { group: 4, code: 401, description: "Unauthorized" },
  { group: 4, code: 402, description: "Payment Required" },
  { group: 4, code: 403, description: "Forbidden" },
  { group: 4, code: 404, description: "Not Found" },
  { group: 4, code: 405, description: "Method Not Allowed" },
  { group: 4, code: 406, description: "Not Acceptable" },
  { group: 4, code: 407, description: "Proxy Authentication Required" },
  { group: 4, code: 408, description: "Request Timeout" },
  { group: 4, code: 409, description: "Conflict" },
  { group: 4, code: 410, description: "Gone" },
  { group: 4, code: 411, description: "Length Required" },
  { group: 4, code: 412, description: "Precondition Failed" },
  { group: 4, code: 413, description: "Payload Too Large" },
  { group: 4, code: 414, description: "URI Too Long" },
  { group: 4, code: 415, description: "Unsupported Media Type" },
  { group: 4, code: 416, description: "Range Not Satisfiable" },
  { group: 4, code: 417, description: "Expectation Failed" },
  { group: 4, code: 418, description: "I'm a Teapot" },
  { group: 4, code: 421, description: "Misdirected Request" },
  { group: 4, code: 422, description: "Unprocessable Entity" },
  { group: 4, code: 423, description: "Locked" },
  { group: 4, code: 424, description: "Failed Dependency" },
  { group: 4, code: 425, description: "Too Early" },
  { group: 4, code: 426, description: "Upgrade Required" },
  { group: 4, code: 428, description: "Precondition Required" },
  { group: 4, code: 429, description: "Too Many Requests" },
  { group: 4, code: 431, description: "Request Header Fields Too Large" },
  { group: 4, code: 451, description: "Unavailable For Legal Reasons" },

  { group: 5, code: 500, description: "Internal Server Error" },
  { group: 5, code: 501, description: "Not Implemented" },
  { group: 5, code: 502, description: "Bad Gateway" },
  { group: 5, code: 503, description: "Service Unavailable" },
  { group: 5, code: 504, description: "Gateway Timeout" },
  { group: 5, code: 505, description: "HTTP Version Not Supported" },
  { group: 5, code: 506, description: "Variant Also Negotiates" },
  { group: 5, code: 507, description: "Insufficient Storage" },
  { group: 5, code: 508, description: "Loop Detected" },
  { group: 5, code: 510, description: "Not Extended" },
  { group: 5, code: 511, description: "Network Authentication Required" }
];
