GET http://localhost:4000/auth?
# &abc=123
# &xyz=456

# content-type: application/json
Authorization: Basic user1:pass1
# Authorization: Bearer abcd
# X-REQUEST-TYPE: GraphQL
# { "body": "1234" }



// ========================================== //
// ================ RESPONSE ================ //
// ========================================== //


