GET http://localhost:4000/auth/basic?
# &abc=123
# &xyz=456

# content-type: application/json
# Authorization: Basic user:pass
# Authorization: Bearer abcd
# X-REQUEST-TYPE: GraphQL
# { "body": "1234" }



// ========================================== //
// ================ RESPONSE ================ //
// ========================================== //


